---
- hosts: "{{ playbook_dir | basename }}"
  become: yes
  tasks:
    - user: name=unprivileged
    - command: echo hi
      become_user: unprivileged
      ignore_errors: yes
    - apt: name=acl
    - command: echo hi
      become_user: unprivileged
